export const SCHEMES = [
  {
    id: 1,
    icon: '🎓',
    category: 'Education • Central',
    title: 'PM Scholarship Scheme 2025',
    description: 'Scholarships for wards of ex-servicemen and coastguard personnel for technical and professional education.',
    eligibility: 'Students, Ex-servicemen wards',
    tags: ['student'],
    benefit: '₹2,500–₹3,000/month',
    deadline: 'June 30, 2026',
    status: 'active',
    overview: 'The Prime Minister\'s Scholarship Scheme provides financial assistance to wards and widows of ex-servicemen and ex-coastguard personnel pursuing higher technical and professional education.',
    eligibilityDetails: [
      'Wards/widows of Ex-Servicemen and Ex-Coastguard personnel',
      'First year of degree courses recognized by AICTE/MCI/DCI/UGC',
      'Minimum 60% marks in qualifying examination',
      'Age limit: 18–25 years',
    ],
    documents: ['Aadhaar Card', 'Ex-serviceman certificate (PPO)', 'Last exam marksheets', 'Bank account (Aadhaar linked)', 'Bonafide certificate'],
    process: ['Register on KSB portal (ksb.gov.in)', 'Fill online application form', 'Upload required documents', 'Submit and track application'],
  },
  {
    id: 2,
    icon: '🌾',
    category: 'Agriculture • Central',
    title: 'PM Kisan Samman Nidhi',
    description: 'Direct income support of ₹6,000 per year to all farmer families, paid in three equal installments.',
    eligibility: 'All farmers',
    tags: ['farmer'],
    benefit: '₹6,000/year',
    deadline: 'Ongoing',
    status: 'active',
    overview: 'PM-KISAN is a Central Sector scheme providing income support to all landholding farmer families to supplement their financial needs for procuring inputs related to agriculture.',
    eligibilityDetails: [
      'All landholding farmer families',
      'Cultivable land in their name',
      'Must have valid Aadhaar',
      'Bank account linked to Aadhaar',
    ],
    documents: ['Aadhaar Card', 'Land records / Khasra', 'Bank passbook', 'Self-declaration form'],
    process: ['Visit PM-KISAN portal (pmkisan.gov.in)', 'Click Farmer Corner → New Farmer Registration', 'Fill and submit form', 'Verify via OTP'],
  },
  {
    id: 3,
    icon: '🏥',
    category: 'Healthcare • Central',
    title: 'Ayushman Bharat PM-JAY',
    description: 'Health insurance coverage of ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
    eligibility: 'BPL families',
    tags: ['healthcare'],
    benefit: '₹5 lakh/year',
    deadline: 'Ongoing',
    status: 'active',
    overview: 'Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana (AB PM-JAY) is the world\'s largest health insurance scheme, covering over 50 crore beneficiaries.',
    eligibilityDetails: [
      'Families listed in SECC 2011 database',
      'Rural: Deprivation criteria',
      'Urban: Occupational criteria',
      'No cap on family size',
    ],
    documents: ['Aadhaar Card', 'Ration Card', 'SECC family ID (if available)', 'Income certificate'],
    process: ['Check eligibility at pmjay.gov.in', 'Visit nearest Ayushman Mitra', 'Get Golden Card issued', 'Use card at empanelled hospitals'],
  },
  {
    id: 4,
    icon: '🚀',
    category: 'Startup • DPIIT',
    title: 'Startup India Seed Fund',
    description: 'Financial assistance up to ₹20 lakh for proof of concept, prototype development, and market entry.',
    eligibility: 'DPIIT-recognized startups',
    tags: ['startup'],
    benefit: 'Up to ₹20 lakh',
    deadline: 'Rolling basis',
    status: 'active',
    overview: 'The Startup India Seed Fund Scheme (SISFS) provides financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization.',
    eligibilityDetails: [
      'DPIIT-recognized startup',
      'Incorporated ≤ 2 years ago at time of application',
      'Not received more than ₹10L in monetary support from government',
      'Must have innovative, scalable business model',
    ],
    documents: ['DPIIT recognition certificate', 'Incorporation certificate', 'PAN', 'Business plan / pitch deck', 'Bank statements'],
    process: ['Apply at seedfund.startupindia.gov.in', 'Select an Incubator', 'Incubator evaluates application', 'Funds disbursed in tranches'],
  },
  {
    id: 5,
    icon: '👩',
    category: 'Women • Central',
    title: 'Mahila Shakti Kendra',
    description: 'Empowering rural women through community participation, skill development training and employment opportunities.',
    eligibility: 'Rural women 18–60',
    tags: ['women'],
    benefit: 'Training + Employment',
    deadline: 'Ongoing',
    status: 'active',
    overview: 'Mahila Shakti Kendra (MSK) empowers rural women through community participation to realize their full potential by creating an environment that promotes awareness, capacity building and convergence.',
    eligibilityDetails: [
      'Women aged 18–60 years',
      'Residing in rural areas',
      'Priority to BPL women',
      'SC/ST women get preference',
    ],
    documents: ['Aadhaar Card', 'Proof of residence', 'Age certificate', 'Income certificate (if applicable)'],
    process: ['Visit nearest Anganwadi Centre', 'Register with block-level officer', 'Complete skill training program', 'Get employment linkage'],
  },
  {
    id: 6,
    icon: '🏠',
    category: 'Housing • Central',
    title: 'Pradhan Mantri Awas Yojana',
    description: 'Affordable housing for all — subsidy on home loans for economically weaker sections and low income groups.',
    eligibility: 'EWS / LIG groups',
    tags: ['housing'],
    benefit: '₹2.67 lakh subsidy',
    deadline: 'Dec 31, 2026',
    status: 'active',
    overview: 'PMAY aims to provide affordable housing to the urban poor with a target of building 2 crore affordable houses for eligible families.',
    eligibilityDetails: [
      'EWS (income up to ₹3L/year) or LIG (₹3L–₹6L/year)',
      'No pucca house anywhere in India',
      'Adult female member as co-owner',
      'First-time home buyers only',
    ],
    documents: ['Aadhaar Card', 'Income certificate', 'Property documents', 'Bank statements (6 months)', 'Self-affidavit (no pucca house)'],
    process: ['Apply at pmaymis.gov.in', 'Select your income category', 'Upload documents', 'Bank verifies and disburses subsidy'],
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'student', label: '🎓 Student' },
  { id: 'farmer', label: '🌾 Farmer' },
  { id: 'women', label: '👩 Women' },
  { id: 'startup', label: '🚀 Startup' },
  { id: 'healthcare', label: '🏥 Healthcare' },
  { id: 'housing', label: '🏠 Housing' },
];

export const LANGUAGES = [
  { code: 'en', flag: '🇮🇳', name: 'English', native: 'English' },
  { code: 'hi', flag: '🇮🇳', name: 'Hindi', native: 'हिन्दी' },
  { code: 'mr', flag: '🇮🇳', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', flag: '🇮🇳', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', flag: '🇮🇳', name: 'Telugu', native: 'తెలుగు' },
  { code: 'bn', flag: '🇮🇳', name: 'Bengali', native: 'বাংলা' },
];
